name: Build Kotlin/Native Multiplatform Releases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        targets:
          - os: ubuntu-latest
            name: linux-x64
          - os: macos-latest
            name: macos-arm64
          - os: windows-latest
            name: windows-x64
    runs-on: ${{ matrix.targets.os }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: oracle

      - name: Build for ${{ matrix.targets.name }}
        run: ./gradlew :linkReleaseExecutableCurrentTarget

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: motd-checker-${{ matrix.targets.name }}-${{ github.sha }}
          path: build/bin/current/releaseExecutable/
